name: fuegos-orinoquia
channels:
  - conda-forge
  - defaults
dependencies:
  - beautifulsoup4
  - gdal
  - geopandas
  - matplotlib
  - netcdf4
  - numpy
  - openpyxl
  - pandas
  - pymannkendall
  - rasterio
  - requests
  - rioxarray
  - seaborn
  - shapely
  - xarray
  - xlrd