name: fuegos-orinoquia
channels:
  - conda-forge
  - defaults
dependencies:
  - beautifulsoup4
  - gdal
  - geopandas
  - matplotlib
  - netcdf4
  - numpy
  - openpyxl
  - pandas
  - plotly
  - pymannkendall
  - pyproj
  - rasterio
  - rasterstats
  - requests
  - rioxarray
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - shapely
  - xarray
  - xlrd
